[package]
name = "roxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.10", features = ["derive"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_toml = "0.0.1"
tokio = { version = "1.39.1", features = ["full"] }
toml = "0.8.15"
